FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Same-origin closed network defaults (override via docker-compose build args).
ARG VITE_ENABLE_EXTERNAL_NETWORK=false
ARG VITE_DATA_SOURCE=internal
ARG VITE_INTERNAL_DATA_API_BASE=/api
ARG VITE_MAP_DEFAULT_TYPE=local
ARG VITE_MAP_SATELLITE_TILES_URL=
ARG VITE_MAP_VECTOR_STYLE_URL=
ARG VITE_MAP_BASIN_STYLE_URL=/frexosm_basin_style.json
ARG VITE_NOMINATIM_ENABLED=false
ARG VITE_NOMINATIM_URL=

ENV VITE_ENABLE_EXTERNAL_NETWORK=$VITE_ENABLE_EXTERNAL_NETWORK
ENV VITE_DATA_SOURCE=$VITE_DATA_SOURCE
ENV VITE_INTERNAL_DATA_API_BASE=$VITE_INTERNAL_DATA_API_BASE
ENV VITE_MAP_DEFAULT_TYPE=$VITE_MAP_DEFAULT_TYPE
ENV VITE_MAP_SATELLITE_TILES_URL=$VITE_MAP_SATELLITE_TILES_URL
ENV VITE_MAP_VECTOR_STYLE_URL=$VITE_MAP_VECTOR_STYLE_URL
ENV VITE_MAP_BASIN_STYLE_URL=$VITE_MAP_BASIN_STYLE_URL
ENV VITE_NOMINATIM_ENABLED=$VITE_NOMINATIM_ENABLED
ENV VITE_NOMINATIM_URL=$VITE_NOMINATIM_URL

RUN npm run build

FROM nginx:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist ./
COPY deploy/webapp.nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1:8080/index.html || exit 1
